### ISSUE TITLE
Jensen–Shannon distance in textstat_dist

### ISSUE THREAD

**Issue by rushkin** [quanteda/quanteda.textstats#15]
Would it be possible to add the Jensen-Shannon divergence (https://en.wikipedia.org/wiki/Jensen%E2%80%93Shannon_divergence) to the methods in textstat_dist?

It is a symmetrized version of the Kullback-Leibler divergence, which is already implemented.

Also, you may want to mention in the documentation that the Kullback-Leibler method is asymmetric (the result will depend on the order of rows in the dfm). In fact, for that reason it is not really a "distance".

Thank you!

**Comment by koheiw** [comment]
Jensen–Shannon and Jeffreys divergence measures are available in `proxyC::dist()` (the underlying function) but we probably do not want to add them to `textstat_dist()` because they are for probability distribution.
