### ISSUE TITLE
Drop legacy functions for keyness

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda.textstats#4]
I think this is the right timing to remove legacy functions.

https://github.com/quanteda/quanteda.textstats/blob/bf61e1954553ca1385f7e5d9536e83619997e118/R/textstat_keyness.R#L139-L153

**Comment by kbenoit** [comment]
That's a good step to take before release. Perhaps move the code to tests, so that we have an independent check on the output of the C++ implementations.
