### ISSUE TITLE
Enable use_nan in proxyC v0.2.1

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda.textstats#41]
Upcoming proxyC v0.21 has a new argument `use_nan` to get `NaN` for vectors that have zero standard deviation. It will replace this part of the code:

https://github.com/quanteda/quanteda.textstats/blob/3302369c2913595564304d99ff769f9884509de9/R/textstat_simil.R#L650-L660

**Comment by koheiw** [comment]
If will also warn when `use_nan  = FALSE`, so it might break tests.

**Comment by kbenoit** [comment]
OK let me know when it's ready for testing and I will add a fix. Will try to change the tests so that it works on both the 0.21 and the current CRAN, then I can update quanteda.textstats so that you won't have any CRAN issues when you submit the proxyC update.

**Comment by koheiw** [comment]
Please see the new behavior in the unit test

https://github.com/koheiw/proxyC/blob/96770543908922f93c431cd8d64df483d85fb74d/tests/testthat/test-simil.R#L113-L134

I have submitted v0.2.1 to CRAN already.

**Comment by kbenoit** [comment]
The latest CRAN checks are now failing on all devel releases as well as 

r-patched-linux-x86_64
r-patched-solaris-x86
r-release-linux-x86_64

(see https://cran.r-project.org/web/checks/check_results_quanteda.textstats.html)

@koheiw you mentioned you'd issue a PR to fix, and we can refresh quanteda as well?

**Comment by koheiw** [comment]
CRAN checks look good now.
