### ISSUE TITLE
Change "hamman" to "hamann"

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda.textstats#44]
See https://github.com/koheiw/proxyC/issues/26.

**Comment by kbenoit** [comment]
🤦‍♂️

Looks like the cite is:

HAMANN, U. (1961): [Merkmalbestand und Verwandtschaftsbeziehungen der Farinosae. Ein Beitragzum System der
Monokotyledonen](https://www.jstor.org/stable/3995266). Willdenowia, 2: 639-768.
