### ISSUE TITLE
Rewrite textstat_readability() and textstat_lexdiv() without data.table?

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda.textstats#5]
This is only a suggestion to reduce dependencies. It should be straightforward if they are taking the sums or means for documents.

**Comment by kbenoit** [comment]
Agree, this could be an issue for the future, if this does not impact performance. Not an issue related to the separation from the main package however.

However we don't add much complexity in terms of second-order dependencies by using **data.table**. The package  has to be compiled on Linux platforms, but does not import any other packages and even the ones it Suggests are minimal.
