### ISSUE TITLE
Should we use [] or subset()?

### ISSUE THREAD

**Issue by koheiw** [quanteda/quanteda.textstats#6]
I noticed that `stat <- NULL` is added to avoid check messages. `subset()` is `NA` safe but `is.na()` is used inside, so `[]` can be used without problems.

https://github.com/quanteda/quanteda.textstats/blob/bf61e1954553ca1385f7e5d9536e83619997e118/R/textstat_simil.R#L426-L439

I also wonder in general which should be used `[]` or `subset()` in writing packages.

**Comment by kbenoit** [comment]
Thought this was simpler than `result[!is.na(result$stat), ]`. Not sure it matters though.
